version: '2.2'

services:

  zoo1:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2184:2181
    #volumes:
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo1/data:/data"
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.11

  zoo2:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2185:2181
    #volumes:
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo2/data:/data"
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.12

  zoo3:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2186:2181
    #volumes:
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo3/data:/data"
    #  - "/Users/shaozhipeng/Development/volume/zkcluster/zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.13

networks:
  dnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1