version: '3.4'

services:

  kafka1:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    #此参数会往容器/etc/hosts和/etc/hostname添加kafka1
    hostname: kafka1
    #docker会默认将container_name的值添加为hostname
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      BROKER_ID: 101
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      #KAFKA_ADVERTISED_HOST_NAME: kafka1
      #KAFKA_ADVERTISED_HOST_NAME: 172.32.0.21
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
    #  - /Users/shaozhipeng/Development/volume/kfkluster/kafka1/logs:/kafka
    #链接未包含在当前docker-compose.yml中的容器
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.32.0.21

  kafka2:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9092
    environment:
      BROKER_ID: 102
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      #KAFKA_ADVERTISED_HOST_NAME: kafka2
      #KAFKA_ADVERTISED_HOST_NAME: 172.32.0.22
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.32.0.22

  kafka3:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9094:9092
    environment:
      BROKER_ID: 103
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      #KAFKA_ADVERTISED_HOST_NAME: kafka3
      #KAFKA_ADVERTISED_HOST_NAME: 172.32.0.23
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.32.0.23

networks:
  default:
    #使用已经存在的网络
    external:
      name: zkc_dnet