version: '3.4'

# 测试
# bin/kafka-topics.sh --create --bootstrap-server kafka1:9092 --replication-factor 1 --partitions 1 --topic topic-test1

services:

  kafka1:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    #此参数会往容器/etc/hosts和/etc/hostname添加kafka1
    hostname: kafka1
    #docker会默认将container_name的值添加为hostname
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      #BROKER_ID: 1
      #TODO
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      #TODO
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo4:2181,zoo5:2181,zoo6:2181
    #volumes:
    #  - /Users/shaozhipeng/Development/volume/kfkluster/kafka1/logs:/kafka
    #链接未包含在当前docker-compose.yml中的容器
    external_links:
      - zoo4
      - zoo5
      - zoo6
    networks:
      default:
        ipv4_address: 172.32.0.21

  kafka2:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9092
    environment:
      #BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo4:2181,zoo5:2181,zoo6:2181
    external_links:
      - zoo4
      - zoo5
      - zoo6
    networks:
      default:
        ipv4_address: 172.32.0.22

  kafka3:
    image: ${KAFKA_SERVER_IMAGE}
    #restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9094:9092
    environment:
      #BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo4:2181,zoo5:2181,zoo6:2181
    external_links:
      - zoo4
      - zoo5
      - zoo6
    networks:
      default:
        ipv4_address: 172.32.0.23

  #https://github.com/yahoo/CMAK/blob/master/conf/application.conf
  kafkaManager:
    image: ${KAFKA_MANAGER_IMAGE}
    #restart: always
    container_name: kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zoo4:2181,zoo5:2181,zoo6:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
      #KAFKA_MANAGER_AUTH_ENABLED: true
      #APPLICATION_SECRET: letmein
      #KM_ARGS: -Djava.net.preferIPv4Stack=true
    links:
      - kafka1
      - kafka2
      - kafka3
    external_links:
      - zoo4
      - zoo5
      - zoo6
    networks:
      default:
        ipv4_address: 172.32.0.31

networks:
  default:
    #使用已经存在的网络
    external:
      name: zkc_dnet